language: php

dist: bionic

env:
  - DB_HOST=localhost DB_USERNAME=travis

addons:
  mariadb: '10.4'

php:
  - '7.2'

matrix:
  fast_finish: true

sudo: true

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  # Database setup
  - sudo mysql -e 'create database vost_api;'
  - sudo mysql -e 'CREATE USER IF NOT EXISTS travis@localhost; GRANT ALL ON *.* TO travis@localhost;'

  # Install project dependencies
  - composer install --no-interaction

  # Clear everything
  - php artisan optimize:clear

  # Create optimised classmap
  - composer dump-autoload -o

  # Check coding standards
  - composer cs-check app
  - composer cs-check config
  - composer cs-check database
  - composer cs-check tests

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --dump-xdebug-filter build/xdebug-filter.php
  - vendor/bin/phpunit --testdox --prepend build/xdebug-filter.php --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/php-coveralls -v

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
