version: '3.7'

services:
  nginx:
    container_name: vost_nginx
    image: nginx:1.14.0-alpine
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - .:/var/www/api.vost.test
    restart: unless-stopped
    networks:
      vost_network:
        aliases:
          - api.vost.test

  api:
    container_name: vost_api
    build: .docker/php
    expose:
      - 9000
    volumes:
      - .:/var/www/api.vost.test
    restart: unless-stopped
    networks:
      - vost_network

  mariadb:
    container_name: vost_mariadb
    image: mariadb:10.4.6
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: vost_api
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    networks:
      - vost_network

  test_database:
    container_name: vost_test_database
    image: mariadb:10.4.6
    environment:
      MYSQL_DATABASE: vost_api
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    restart: unless-stopped
    networks:
      - vost_network

  redis:
    container_name: vost_redis
    image: redis:4.0.9-alpine
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    networks:
      - vost_network

networks:
  vost_network:
